Repository plonegovbr/plonegovbr.portal_edu, pull requests merged in 2023-06, with the labels that each got.

#1 Adiciona schema.json e um post_handler a distribuição
  Makefile
  news/12.feature
  src/plonegovbr/portal_edu/distributions.zcml
  src/plonegovbr/portal_edu/distributions/portal_edu/schema.json
  src/plonegovbr/portal_edu/distributions/portal_edu/schema.json_example
  src/plonegovbr/portal_edu/handler.py
  src/plonegovbr/portal_edu/profiles/default/registry/plone.i18n.interfaces.ILanguageSchema.xml
  tests/registration/test_distribution.py
Labels: enhancement

#2 Corrige exibição do painel de controle do PortalBrasil.edu
  news/13.bugfix
  src/plonegovbr/portal_edu/profiles/default/controlpanel.xml
  tests/controlpanel/test_controlpanel_pb_edu.py
Labels: bug

#3 Gera imagem ghcr.io/ploneorgbr/portal_edu
  .dockerignore
  .github/workflows/meta.yml
  Dockerfile
  MANIFEST.in
  Makefile
  news/25.internal
  requirements-docker.txt
  setup.py
Labels: ci/cd

#4 Refatora código do post_handler da distribuição edu.
  src/plonegovbr/portal_edu/distributions.zcml
  src/plonegovbr/portal_edu/handlers.py
Labels: enhancement
